version: "3"
services:
  myredis:
    image: redis:latest
    deploy:
      replicas: 3
    networks:
      - edu_forum_mynet

  php:
    image: alexyun0429/edu_forum_php:1.0.0
    volumes:
      - ./php:/var/www/htdocs
    deploy:
      replicas: 8
    networks:
      - edu_forum_mynet

  mynginx:
    image: alexyun0429/edu_forum_nginx:1.0.0
    volumes:
      - ./php:/var/www/htdocs
    ports:
      - "8080:80"
    depends_on:
      - php
    deploy:
      replicas: 8
    networks:
      - edu_forum_mynet

networks:
  edu_forum_mynet:
    external: true
