version: "3"
services:
  myredis:
    image: redis:latest
    networks:
      - edu_forum_mynet

  php:
    image: alexyun0429/edu_forum_php
    volumes:
      - ./php:/var/www/htdocs
    deploy:
      replicas: 2
    networks:
      - edu_forum_mynet

  mynginx:
    image: alexyun0429/edu_forum_nginx
    volumes:
      - ./php:/var/www/htdocs
    ports:
      - "8080:80"
    depends_on:
      - php
    deploy:
      replicas: 2
    networks:
      - edu_forum_mynet

networks:
  edu_forum_mynet:
    external: true
