version: "3"
services:
  mysql:
    image: mariadb:latest
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: e9289ebcad2ae49d6e4d127b
      MYSQL_DATABASE: edu_forum
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: php
      PMA_PASSWORD: php
    networks:
      - mynet

networks:
  mynet:
    external: true
