version: "3"
services:
  mysql:
    image: mariadb:latest
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: edu_forum
      MYSQL_USER: php
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    networks:
      - edu_forum_mynet

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: php
      PMA_PASSWORD: php
    networks:
      - edu_forum_mynet

networks:
  edu_forum_mynet:
    external: true
