# Use an official PHP runtime as a parent image
FROM php:8.2-fpm

# Set environment variables
ENV TZ=Australia/Brisbane

# Set maintainer information
LABEL maintainer="JaeWon Yun jaewon.yun@uqconnect.edu.au"

# Install necessary packages
RUN apt-get update && apt-get install -y software-properties-common --no-install-recommends \
    && add-apt-repository ppa:ondrej/php && apt-get update \
    && apt-get install -y nginx apt-utils curl git build-essential libssl-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libicu-dev

# Install PHP extensions
RUN docker-php-ext-install intl mysqli pdo pdo_mysql zip mbstring \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-configure intl

# Copy Nginx configuration file
COPY sites-available/elioter.conf /etc/nginx/sites-available/default

# Copy the current directory contents into the container at /var/www/html
COPY . /var/www/html

# Expose port 80 for Nginx
EXPOSE 80

# Set working directory to root folder of website
WORKDIR /var/www/html

# Start Nginx and PHP-FPM with entrypoint command
ENTRYPOINT service php8.2-fpm start && nginx -g "daemon off;"
